GET http://localhost:3001/notes

###

POST http://localhost:3001/note/new
Content-Type: application/json

{
    "title": "New data test wednesday",
    "text": "does the category work? the date?",
    "complete": false,
    "category": "work"
}

###

DELETE http://localhost:3001/note/delete/6189ff46eca0104257736f0a

###

PUT http://localhost:3001/note/complete/6189febdce9f21741380ca0d